// Otomatik üretildi: "yks konuları.docx" içindeki konu listesi.
const TOPICS = {
  "TYT": {
    "Türkçe": [
      "Sözcükte Anlam",
      "Söz Yorumu",
      "Deyim ve Atasözü",
      "Cümlede Anlam",
      "Paragraf",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı/Ekler",
      "Sözcük Türleri",
      "İsimler",
      "Zamirler",
      "Sıfatlar",
      "Zarflar",
      "Edat – Bağlaç – Ünlem",
      "Fiiller",
      "Fiilde Anlam (Kip-Kişi-Yapı)",
      "Ek Fiil",
      "Fiilimsi",
      "Fiilde Çatı",
      "Sözcük Grupları",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozukluğu"
    ],
    "Tarih": [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Ortaçağ’da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti(1300-1453)",
      "Dünya Gücü Osmanlı Devleti (1453-1600)",
      "Yeni Çağ Avrupa Tarihi",
      "Yakın Çağ Avrupa Tarihi",
      "Osmanlı Devletinde Arayış Yılları",
      "18. Yüzyılda Değişim ve Diplomasi",
      "En Uzun Yüzyıl",
      "Osmanlı Kültür ve Medeniyeti",
      "20. Yüzyılda Osmanlı Devleti",
      "I. Dünya Savaşı",
      "Mondros Ateşkesi, İşgaller ve Cemiyetler",
      "Kurtuluş Savaşına Hazırlık Dönemi",
      "I. TBMM Dönemi",
      "Kurtuluş Savaşı ve Antlaşmalar",
      "II. TBMM Dönemi ve Çok Partili Hayata Geçiş",
      "Türk İnkılabı",
      "Atatürk İlkeleri",
      "Atatürk Dönemi Türk Dış Politikası"
    ],
    "Coğrafya": [
      "Doğa ve İnsan",
      "Dünya’nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "Atmosfer ve Sıcaklık",
      "İklimler",
      "Basınç ve Rüzgarlar",
      "Nem, Yağış ve Buharlaşma",
      "İç Kuvvetler / Dış Kuvvetler",
      "Su – Toprak ve Bitkiler",
      "Nüfus",
      "Göç",
      "Yerleşme",
      "Türkiye’nin Yer Şekilleri",
      "Ekonomik Faaliyetler",
      "Bölgeler",
      "Uluslararası Ulaşım Hatları",
      "Çevre ve Toplum",
      "Doğal Afetler"
    ],
    "Felsefe": [
      "Felsefenin Konusu",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Din, Kültür ve Medniyet",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi"
    ],
    "Din": [
      "İnanç",
      "İbadet",
      "Ahlak ve Değerler",
      "Din, Kültür ve Medniyet",
      "Hz. Mhammed (S.A.V.)",
      "Vahiy ve Akıl",
      "Dünya ve Ahiret",
      "Kur’an'a göre Hz. Muhammed (S.A.V.)",
      "İnançla İlgili Meseleler",
      "Yahudilik ve Hristiyanlık",
      "İslam ve Bilim",
      "Anadolu da İslam",
      "İslam Düşüncesinde Tasavvufi Yorumlar",
      "Güncel Dini Meseler",
      "Hint ve Çin Dinleri"
    ],
    "Matematik": [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB – EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Sayı Problemleri",
      "Kesir Problemleri",
      "Yaş Problemleri",
      "Hareket Hız Problemleri",
      "İşçi Emek Problemleri",
      "Yüzde Problemleri",
      "Kar Zarar Problemleri",
      "Karışım Problemleri",
      "Grafik Problemleri",
      "Rutin Olmayan Problemleri",
      "Kümeler – Kartezyen Çarpım",
      "Mantık",
      "Fonskiyonlar",
      "Polinomlar",
      "2.Dereceden Denklemler",
      "Permütasyon ve Kombinasyon",
      "Olasılık",
      "Veri – İstatistik"
    ],
    "Geometri": [
      "Temel Kavramlar",
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Açıortay",
      "Kenarortay",
      "Eşlik ve Benzerlik",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler",
      "Dörtgenler",
      "Deltoid",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Dikdörtgen",
      "Kare",
      "Yamuk",
      "Çember ve Daire",
      "Çemberde Açı",
      "Çemberde Uzun",
      "Dairede Çevre ve Alan",
      "Analitik Geometri",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşüm Geometrisi",
      "Katı Cisimler",
      "Prizmalar",
      "Küp",
      "Silindir",
      "Piramit",
      "Koni",
      "Küre",
      "Çemberin Analitiği"
    ],
    "Fizik": [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket ve Kuvvet",
      "Dinamik",
      "İş, Güç ve Enerji",
      "Elektrik",
      "Manyetizma",
      "Dalgalar",
      "Optik"
    ],
    "Kimya": [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları",
      "Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asit, Baz ve Tuz",
      "Kimya Her Yerde"
    ],
    "Biyoloji": [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organeller – Madde Geçişleri",
      "Canlıların Sınıflandırılması",
      "Hücrede Bölünme – Üreme",
      "Kalıtım",
      "Bitki Biyolojisi",
      "Ekosistem"
    ]
  },
  "AYT": {
    "Edebiyat": [
      "Anlam Bilgisi",
      "Dil Bilgisi",
      "Güzel Sanatlar ve Edebiyat",
      "Metinlerin Sınıflandırılması",
      "Şiir Bilgisi",
      "Edebi Sanatlar",
      "Türk Edebiyatı Dönemleri",
      "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Tanzimat Edebiyatı",
      "Servet-i Fünun Edebiyatı",
      "Fecr-i Ati Edebiyatı",
      "Milli Edebiyat",
      "Cumhuriyet Dönemi Edebiyatı",
      "Edebiyat Akımları",
      "Dünya Edebiyatı"
    ],
    "Tarih": [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ’da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet’i Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Beylikten Devlete Osmanlı Medeniyeti",
      "Dünya Gücü Osmanlı",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Klasik Çağda Osmanlı Toplum Düzeni",
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Sermaye ve Emek",
      "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
      "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
      "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
      "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
      "Toplumsal Devrim Çağında Dünya ve Türkiye",
      "XXI. Yüzyılın Eşiğinde Türkiye ve Dünya"
    ],
    "Coğrafya": [
      "Ekosistem",
      "Biyoçeşitlilik",
      "Biyomlar",
      "Ekosistemin Unsurları",
      "Enerji Akışı ve Madde Döngüsü",
      "Ekstrem Doğa Olayları",
      "Küresel İklim Değişimi",
      "Nüfus Politikaları",
      "Türkiye’de Nüfus ve Yerleşme",
      "Ekonomik Faaliyetler ve Doğal Kaynaklar",
      "Göç ve Şehirleşme",
      "Türkiye Ekonomisi",
      "Türkiye’nin Ekonomi Politikaları",
      "Türkiye Ekonomisinin Sektörel Dağılımı",
      "Türkiye’de Tarım",
      "Türkiye’de Hayvancılık",
      "Türkiye’de Madenler ve Enerji Kaynakları",
      "Türkiye’de Sanayi",
      "Türkiye’de Ulaşım",
      "Türkiye’de Ticaret ve Turizm",
      "Geçmişten Geleceğe Şehir ve Ekonomi",
      "Türkiye’nin İşlevsel Bölgeleri ve Kalkınma Projeleri",
      "Hizmet Sektörünün Ekonomideki Yeri",
      "Küresel Ticaret",
      "Bölgeler ve Ülkeler",
      "İlk Uygarlıklar",
      "Kültür Bölgeleri ve Türk Kültürü",
      "Sanayileşme Süreci: Almanya",
      "Tarım ve Ekonomi İlişkisi Fransa – Somali",
      "Ülkeler Arası Etkileşim",
      "Jeopolitik Konum",
      "Çatışma Bölgeleri",
      "Küresel ve Bölgesel Örgütler",
      "Çevre ve Toplum",
      "Çevre Sorunları ve Türleri",
      "Madenler ve Enerji Kaynaklarının Çevreye Etkisi",
      "Doğal Kaynakların Sürdürülebilir Kullanımı",
      "Ekolojik Ayak İzi",
      "Doğal Çevrenin Sınırlılığı",
      "Çevre Politikaları",
      "Çevresel Örgütler",
      "Çevre Anlaşmaları",
      "Doğal Afetler"
    ],
    "Matematik": [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB - EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Problemler",
      "Kümeler",
      "Kartezyen Çarpım",
      "Mantık",
      "Fonskiyonlar",
      "Polinomlar",
      "2.Dereceden Denklemler",
      "Permütasyon ve Kombinasyon",
      "Binom ve Olasılık",
      "İstatistik",
      "Karmaşık Sayılar",
      "2.Dereceden Eşitsizlikler",
      "Parabol",
      "Trigonometri",
      "Logaritma",
      "Diziler",
      "Limit",
      "Türev",
      "İntegral",
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen",
      "İkizkenar Üçgen",
      "Eşkenar Üçgen",
      "Açıortay",
      "Kenarortay",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler",
      "Dörtgenler",
      "Deltoid",
      "Paralelkenar",
      "Eşkenar Dörtgen",
      "Dikdörtgen",
      "Kare",
      "İkizkenar",
      "Yamuk",
      "Çember ve Daire",
      "Analitik Geometri",
      "Noktanın Analitiği",
      "Doğrunun Analitiği",
      "Dönüşüm Geometrisi",
      "Katı Cisimler (Uzay Geometri)",
      "Dikdörtgenler Prizması",
      "Küp",
      "Silindir",
      "Piramit",
      "Koni",
      "Küre",
      "Çemberin Analitiği"
    ]
  }
};
const LESSONS = {"TYT": ["Türkçe", "Tarih", "Coğrafya", "Felsefe", "Din", "Matematik", "Geometri", "Fizik", "Kimya", "Biyoloji"], "AYT": ["Edebiyat", "Tarih", "Coğrafya", "Matematik"]};
